### ISSUE TITLE
cli download

### ISSUE THREAD

**Issue by abonillasuse** [intel-iot-devkit/aws-iot-intel#3]
I can't find aws-iot-cli.zip - is there any other location or method to install it?

**Comment by w4ilun** [comment]
@abonillasuse that step is actually not necessary with the latest version (AWS CLI 1.8.12 as of October 13, 2015), you can skip this step. Verify that everything installed correctly by running "aws iot help".

**Comment by abonillasuse** [comment]
Not quite, I think

 MacPro in ~
○ → aws --version
aws-cli/1.8.12 Python/2.7.10 Darwin/15.0.0

 MacPro in ~
○ → aws iot help
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument command: Invalid choice, valid choices are:

**Comment by w4ilun** [comment]
@abonillasuse the provided instructions were intended for the Intel Edison platform, but you should still be able to use AWS IoT with 1.8.12 on your MacPro (Refer to release notes found here: https://aws.amazon.com/releasenotes/CLI/9215180270435262) . Please follow instructions here if you are still running into issues: http://docs.aws.amazon.com/cli/latest/userguide/installing.html
